id: I446AFF9A
legacy_id: P000514
ocr_import_info:
  bdrc_scan_id: W1KG10580
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:16:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:45:45.402498+00:00'
last_modified: 2022-08-31 10:46:25.900725
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10580
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10580
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་བདག་བཀའ་འབུམ།
  author: བསམ་གཏན་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.7797217972362908
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I1KG10661:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10661
      total_pages: 282
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10661.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7850252003823833
    legacy_id: v001
  I1KG10662:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10662
      total_pages: 314
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10662.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7725227580473645
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
